name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc nasm make qemu-system-i386 genisoimage python3
      
    - name: run build
      run: make iso
    
    - name: commit build
      run: |
        cd ../
        git config --local user.name "esolangs"
        git clone https://${GIT_TOKEN}@github.com/esolangs/profanOS-build.git
        cd profanOS-build
        mv ../profanOS/profanOS.iso .
        git add profanOS.iso
        git commit -m "auto-build"

    - name: push build
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
