name: build iso

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: install dependencies
      run: sudo apt-get install -y gcc nasm make python3
      
    - name: build img
      run: |
        wget https://raw.githubusercontent.com/elydre/elydre/main/projet/profan/version.py
        VERSION=$(python3 version.py)
        echo "PROFAN_ISO=profanOS-$VERSION.iso" >> $GITHUB_ENV
        echo "PROFAN_VER=profanOS v$VERSION" >> $GITHUB_ENV
        make iso
        cp profanOS.iso profanOS-$VERSION.iso

    - name: push img to github
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GIT_TOKEN }}
      with:
        source_file: ${{ env.PROFAN_ISO }}
        destination_repo: 'esolangs/profanOS-build'
        destination_folder: 'post55-iso'
        user_email: 'pf4_@gmail.com'
        user_name: 'esolangs'
        commit_message: 'new release'

    - name: Release to GitHub
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: ${{ env.PROFAN_VER }}
        automatic_release_tag: latest
        repo_token: "${{ secrets.GIT_TOKEN }}"
        files: |
          profanOS.elf
          profanOS.iso
