name: build iso

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc nasm make qemu-system-i386 genisoimage python3
      
    - name: build iso
      run: |
        make iso
        wget https://raw.githubusercontent.com/elydre/elydre/main/projet/lite/profan_version.py
        profan_ver=$(python3 profan_version.py)
        export profan_ver
        echo $profan_ver
        cp profanOS.iso profanOS-$profan_ver.iso
      env:
        - name: profan_ver
          value: $profan_ver
      
    
    - name: push iso to github
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GIT_TOKEN }}
      with:
        source_file: 'profanOS-${{ env.profan_ver }}.iso'
        destination_repo: 'esolangs/profanOS-build'
        user_email: 'pf4_@gmail.com'
        user_name: 'esolangs'
        commit_message: 'iso update'

    - name: update iso on website
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GIT_TOKEN }}
      with:
        source_file: 'profanOS.iso'
        destination_repo: 'elydre/elydre.github.io'
        destination_folder: 'profan/img'
        user_email: 'pf4_@gmail.com'
        user_name: 'esolangs'
        commit_message: 'iso update'

    - name: Release to GitHub
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Latest Release
        automatic_release_tag: latest
        repo_token: "${{ secrets.GIT_TOKEN }}"
        files: |
          profanOS.iso
          profanOS.bin
