name: build img

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: install dependencies
      run: sudo apt-get install -y gcc nasm make python3
      
    - name: build img
      run: |
        wget https://raw.githubusercontent.com/elydre/elydre/main/projet/profan-tools/version.py
        echo "PROFAN_IMG=profanOS-$(python3 version.py).img" >> $GITHUB_ENV
        echo "PROFAN_VER=profanOS v$(python3 version.py)" >> $GITHUB_ENV
        make
        mv profanOS.img profanOS-nr.img
        dd if=/dev/zero of=profanOS.img bs=1k count=1440
        dd if=profanOS-nr.img of=profanOS.img conv=notrunc
        cp profanOS.img ${{ env.PROFAN_IMG }}

    - name: push img to github
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GIT_TOKEN }}
      with:
        source_file: ${{ env.PROFAN_IMG }}
        destination_repo: 'esolangs/profanOS-build'
        destination_folder: 'img'
        user_email: 'pf4_@gmail.com'
        user_name: 'esolangs'
        commit_message: 'new release'

    - name: Release to GitHub
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: ${{ env.PROFAN_VER }}
        automatic_release_tag: latest
        repo_token: "${{ secrets.GIT_TOKEN }}"
        files: |
          profanOS-nr.img
          profanOS.img
