name: build iso

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc nasm make qemu-system-i386 genisoimage python3
      
    - name: run build
      run: make iso
    
    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GIT_TOKEN }}
      with:
        source_file: 'profanOS.iso'
        destination_repo: 'esolangs/profanOS-build'
        user_email: 'pf4_@gmail.com'
        user_name: 'esolangs'
        commit_message: 'auto build'
